server:
  port: 8000

spring:
  application:
    name: forex-service
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  h2:
    console:
      enabled: true
