server:
  port: 8501
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/

spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: microservices

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG