server:
  port: 8502

spring:
  application:
    name: ticket-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
      url: jdbc:mysql://localhost:3306/microservices
      username: root
      password: 1999Aqil

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/